# Development environment
version: '2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "3000:80"
    links:
      - mysql:db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'app_dev'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: app_dev
      DB_USERNAME: root
      DB_PASSWORD:
    volumes:
      - .:/app
      - /app/vendor
      - /app/public
    ports:
      - "8080:80"
    links:
      - mysql
    depends_on:
      - mysql